### ISSUE TITLE
Ping counter overlaps usernames in Tab Ping

### ISSUE THREAD

**Issue by NorthernChicken** [Natxo09/Fabric-Mods#1]
![pingcounterbug](https://github.com/Natxo09/Fabric-Mods/assets/144752748/eafb94f9-cf89-4a3a-b7fe-107c73bba7c4)

As the name and picture suggest. This is an issue on servers without custom tab lists plugins as well.

**Comment by Natxo09** [comment]
> ![pingcounterbug](https://github.com/Natxo09/Fabric-Mods/assets/144752748/eafb94f9-cf89-4a3a-b7fe-107c73bba7c4)
> 
> 
> 
> As the name and picture suggest. This is an issue on servers without custom tab lists plugins as well.

Are you on the 1.21 version?

**Comment by NorthernChicken** [comment]
yes.

**Comment by Natxo09** [comment]
Okay, I think I have it now. I'll upload the new version. Please confirm if it works well, and I'll close the issue. Thank you very much!

**Comment by NorthernChicken** [comment]
![Screenshot 2024-06-18 075538](https://github.com/Natxo09/Fabric-Mods/assets/144752748/e0df48b9-9461-486f-b0df-28a0ff35cc24)
I can confirm it works well now. Thanks!
